config/routes.rb
Rails.application.routes.draw do
  root to: "manufacturers#index"
  resources :manufacturers do
    resources :cars
  end

end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :manufacturer

  validates :manufacturer, presence: true
  validates :color, presence: true
  validates :mileage, numericality: { only_integer: true }
  validates :year, numericality:  { greater_than_or_equal_to: 1920 }
end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
  has_many :cars

  validates :name, presence: true, uniqueness: { message: "This manufacturer is already existed." }
  validates :country, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end

  def new
    @car = Car.new
    @manufacturer = Manufacturer.find(params[:manufacturer_id])
  end

  def create
    @car = Car.new(car_params)
    @manufacturer = Manufacturer.find(params[:manufacturer_id])
    if @car.save
      redirect_to manufacturer_cars_path
      flash[:notice] = "Your record has been created successfully!"
    else
      flash[:notice] = "Your record could not be completed"
      render "new"
    end
  end

  def car_params
    params.require(:car).permit(:manufacturer_id, :color, :year, :mileage, :description)
  end
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  def index
    @manufacturers = Manufacturer.all
    @cars = Car.all
  end

  def new
    @manufacturer = Manufacturer.new
  end

  def show
    @manufacturer = Manufacturer.find(params[:id])
  end

  def create
    @manufacturer = Manufacturer.new(manufacturer_params)

    if @manufacturer.save
      redirect_to manufacturers_path
      flash[:notice] = "Your record has been created successfully!"
    else
      flash[:notice] = "Your record could not be completed"
      render "new"
    end
  end

  def manufacturer_params
    params.require(:manufacturer).permit(:name, :country)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/index.html.erb
<h2>List of cars:</h2>

<div>
  <% @cars.each do |car| %>
    <div>
      <%= car.color %> --- <%= car.mileage %> --- <%= car.year %>
    </div>
  <% end %>
</div>

app/views/cars/new.html.erb
<h2> Add a new car </h2>

<%= form_for [@manufacturer, @car] do |f| %>

  <% if @car.errors.any? %>
    <p><%= "#{@car.errors.count} prevented your record from being saved:" %></p>
    <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= f.label :manufacturer_id %>
  <%= f.collection_select :manufacturer_id, Manufacturer.all.order(:name), :id, :name, include_blank: true %>
  </div>

  <div>
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>

   <div>
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </div>

  <div>
    <%= f.label :mileage %><br>
    <%= f.text_field :mileage %>
  </div>

  <div>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>

  <%= f.submit "Add car" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SystemCheck</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div>
    <%= link_to "Home", root_path %> ||
    <%= link_to "Add new manufacturer", new_manufacturer_path %>
  </div>
  <div>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>

app/views/manufacturers/index.html.erb
<h2>List of manufacturers:</h2>

<% @manufacturers.each do |manu| %>
  <div>
    <%= link_to manu.name, manufacturer_path(manu)%>
  </div>
<% end %>

<hr>
<div>
  <h2>Lists of all car in stock: </h2>
  <% @cars.each do |car| %>
    <div>
      <%= car.manufacturer.name %>-- <%= car.color %> -- <%= car.mileage %> -- <%= car.year %>
    </div>
  <% end %>
</div>

app/views/manufacturers/new.html.erb
<h2>Add a new manufacturer</h2>
<%= form_for @manufacturer do |f| %>

  <% if @manufacturer.errors.any? %>
    <p><%= "#{@manufacturer.errors.count} prevented your matchup from being saved:" %></p>
    <ul>
      <% @manufacturer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>

  <%= f.submit "Add manufacturer" %>
<% end %>

app/views/manufacturers/show.html.erb
<div>
  <h2><%= @manufacturer.name %></h2>
  <strong>Made in:</strong>
  <%= @manufacturer.country %>
</div>
<hr>
<div>
  <h2>
    <%= link_to "Click here to add a new car:", new_manufacturer_car_path(@manufacturer) %>
  </h2>
</div>